### PR TITLE
Allow tracing the performance of middleware

### PR DESCRIPTION
**Pull request by benlangfeld**
In a consuming application, when debugging slow responses to subscribing clients, it is useful to know where time is being spent in MessageBus middleware. This functionality allows hooking in a consumer-application-specific tracing mechanism, such as [NewRelic's `#trace_execution_scoped`](https://www.rubydoc.info/github/newrelic/newrelic-ruby-agent/NewRelic/Agent/MethodTracer#trace_execution_scoped-instance_method).

Tracking some attributes of a connection will allow us to spot patterns in use of long polling/chunked encoding, etc.

Our use case involves `NewRelic::Agent::MethodTracer.trace_execution_scoped` and `NewRelic::Agent.add_custom_attributes` but the implementation here is agnostic of the tool used to record this data.

### CODE REVIEW

**Review by rafbgarcia — APPROVED** [review]

**Comment by benlangfeld** [comment]
Hey @SamSaffron , I hope you're well. If you are in agreement and were to have time to get this in a release, I would very much appreciate it :)

**Comment by SamSaffron** [comment]
@jeremyevans I hope you have some time for a bit of advice here. 

I have a lot of general reticence of adding instrumentation that adds general cost to all execution (even when nobody is tracing) 

My general preference is to specify a "contract" for the various tracers out there, then the tracers can prepend specific methods or rewrite them safely. 

So if there is a registry saying: 

"message_bus#on_request" is in the class  MessageBus::Rack::Middleware #on_request we can define our own helper for rewriting these methods with instrumentation.


I am curious on your position on this problem of both what fidelity of instrumentation should be offered and implementation style. 

An interesting alternative may be to do a minor internal refactor and offer a "message-bus-tracing" gem.

**Comment by jeremyevans** [comment]
My preference would be an approach that has zero or almost zero cost if not enabled, even if it significantly increases the cost when enabled.

This doesn't necessarily have to be a separate gem, we could do an internal refactor and keep it in the same gem, just have it be required separately.  That assumes we want to maintain the tracing ourselves. If we don't want to maintain it ourselves, we should have it be a separate gem.

Ideally, a user could just extend/include the necessary objects or classes to enable the tracing, having methods call `super` as appropriate, without having to modify the internals.  However, I'm not sure to what extent that is possible in this case.

**Comment by benlangfeld** [comment]
@SamSaffron @jeremyevans Do you guys have any references to precedent that I could look at to come up with an implementation that satisfies your requirements?

**Comment by jeremyevans** [comment]
To be clear, I don't have any requirements, only advice/recommendations.  In terms of the patch itself, my recommendation would be: instead of wrapping specific blocks of code with `@bus.trace`, extract private methods, so that those methods could be wrapped (calling `super`) to get the desired effect.  Example, replace:

```ruby
      user_id = @bus.user_id_lookup.call(env) if @bus.user_id_lookup
      group_ids = @bus.group_ids_lookup.call(env) if @bus.group_ids_lookup
      site_id = @bus.site_id_lookup.call(env) if @bus.site_id_lookup
```

with:

```
  user_id, group_ids, site_id = handle_lookups(env)
```

Then `handle_lookups` could be overridden by the tracing support.

Note that every extracted method has a small cost.  You would only want to extract a method to allow for additional flexibility if the benefit for the few users that need tracing is greater than the cost to all users that do not.

FWIW, in the above code example, if you wanted to trace, you could just have three separate traces, one inside each of the lookup procs.  That requires no code changes.

**Comment by benlangfeld** [comment]
> To be clear, I don't have any requirements, only advice/recommendations. In terms of the patch itself, my recommendation would be: instead of wrapping specific blocks of code with `@bus.trace`, extract private methods, so that those methods could be wrapped (calling `super`) to get the desired effect. Example, replace:
> 
> ```ruby
>       user_id = @bus.user_id_lookup.call(env) if @bus.user_id_lookup
>       group_ids = @bus.group_ids_lookup.call(env) if @bus.group_ids_lookup
>       site_id = @bus.site_id_lookup.call(env) if @bus.site_id_lookup
> ```
> 
> with:
> 
> ```
>   user_id, group_ids, site_id = handle_lookups(env)
> ```
> 
> Then `handle_lookups` could be overridden by the tracing support.
> 
> Note that every extracted method has a small cost. You would only want to extract a method to allow for additional flexibility if the benefit for the few users that need tracing is greater than the cost to all users that do not.
> 
> FWIW, in the above code example, if you wanted to trace, you could just have three separate traces, one inside each of the lookup procs. That requires no code changes.

Thanks for the detail @jeremyevans ! By "could be overridden by the tracing support" do you mean simply having consuming applications subclass, or do you imagine something more involved?

**Comment by jeremyevans** [comment]
Subclassing or including/prepending a module to the main class.

FWIW, my libraries that have need for extensibility (e.g. Sequel, Roda, Rodauth) have their own plugin systems to make things like this easier.  However, I'm not sure if that's a route that @SamSaffron wants to take, as that adds complexity too.  It's only worth it if there are sufficient plugins to justify it.  For example, if most of MessageBus's optional features were implemented as separate plugins, and users could pick only the plugins they need for their environment.

**Comment by SamSaffron** [comment]
I love the plugin design @jeremyevans stuff has, but I worry it is a bit too big for what we need here. Maybe if we just prep for this longer term?

How does something like this look? 

https://gist.github.com/188f16bcd9a5efc7b2c9a74e14d833a5

I love the idea of having a "registry" of sorts cause it gives us lots of flexibility.

**Comment by jeremyevans** [comment]
@SamSaffron Something like that should be fine.  The main change required to MessageBus would be extract methods for all behavior that you want to instrument.

**Comment by SamSaffron** [comment]
Sorry Ben, closing this cause I would prefer a registry based approach here so we keep instrumentation further away from the code. 

https://gist.github.com/SamSaffron/188f16bcd9a5efc7b2c9a74e14d833a5#file-demo-rb-L27-L28

**Pull request closed without merging**
