### PR TITLE
FEATURE: Support UMD and NPM

### PR DESCRIPTION
**Pull request by eviltrout**
This gives us a package.json we can publish to NPM as well as a
universal module definition that supports browser globals as well as
ES6 imports in Ember CLI via auto import.

### CODE REVIEW

**Comment by SamSaffron** [comment]
Looks good, merge at will, maybe add a rake task to publish to NPM?

**Comment by eviltrout** [comment]
@SamSaffron I didn't think that was necessary because npm is already a command line task - it's `npm publish`. Would you prefer a rake task that runs that simple command?

**Comment by SamSaffron** [comment]
I think ... we should inject into `bundle exec rake:release` just so we don't forget when we do new gem releases. 

The tricky thing though is that most gem releases do not touch the js bundle... but some do.

There is an advantage though of having version parity, so you know for sure that message bus 1.2.1 works well with npm message bus 1.2.1 ... eliminates a bunch of thinking.

**Comment by eviltrout** [comment]
Added here:

https://github.com/discourse/message_bus/commit/7847936a892eddde0fae1b7d2e28a0bae0452a21

**Pull request merged**
